baseurl: /12Caesars/      # place folder name if the site is served in a subfolder

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "/12Caesars/"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "/12Caesars/"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/12Caesars"
    values:
      layout: "default"